DO $$
    BEGIN
      IF EXISTS(SELECT *
        FROM information_schema.columns
        WHERE table_name='core_countries')
      THEN
       INSERT INTO public.core_countries(code,label,nationality_label,phone_code, version)
	VALUES 
	 ('AFG', 'Afghanistan','Afghane',93,1),
	 ('ZAF', 'Afrique du Sud','Sud-Africaine',27,1),
	 ('ALB', 'Albanie','Albanaise',355,1),
	 ('DZA', 'Algérie','Algérienne',213,1),
	 ('DEU', 'Allemagne','Allemande',49,1),
         ('AND', 'Andorre','Andorrane',376,1),
	 ('AG0', 'Angola','Angolaise',244,1),
         ('ATG', 'Antigua-et-Barbuda','Antiguais',1,1),
         ('SAU', 'Arabie Saoudite','Saoudienne',966,1),
         ('ARG', 'Argentine','Argentine',54,1),
         ('ARM', 'Arménie','Arménienne',374,1),
         ('AUS', 'Australie','Australienne',61,1),
         ('AUT', 'Autriche','Autrichienne',43,1),
         ('AZE', 'Azerbaïdjan','Azerbaïdjanaise',994,1),
         ('BHS', 'Bahamas','Bahamienne',1,1),
         ('BHR', 'Bahreïn','Bahreïni',973,1),
         ('BGD', 'Bangladesh','Bangladeshie',880,1),
         ('BRB', 'Barbade','Barbadienne',1,1),
         ('PLW', 'Belau / Palau / Palaos','Palaos',680,1),
         ('BEL', 'Belgique','Belge',32,1),
         ('BLZ', 'Belize','Bélizienne',501,1),
	 ('BEN', 'Bénin','Béninoise',229,1),
         ('BTN', 'Bhoutan','Bhotia',975,1),
         ('BLR', 'Biélorussie','Biélorusse',375,1),
         ('MMR', 'Birmanie','Birmane',95,1),
         ('BOL', 'Bolivie','Bolivienne',591,1),
         ('BIH', 'Bosnie-Herzégovine','Bosniaque',387,1),
         ('BWA', 'Botswana','Botswanaise',267,1),
	 ('BRA', 'Brésil','Brésilienne',55,1),
         ('BRN', 'Brunei','Brunéienne',673,1),
         ('BGR', 'Bulgarie','Bulgare',359,1),
	 ('BFA', 'Burkina-Faso','Burkinabée',226,1),
	 ('BDI', 'Burundi','Burundaise',257,1),
         ('KHM', 'Cambodge','Cambodgienne',855,1),
	 ('CMR', 'Cameroon','Camerounaise',237,1),
         ('CAN', 'Canada', 'Canadienne',1,1),
	 ('CPV', 'Cap-Vert','Cap-Verdienne',238,1),
	 ('CAF', 'République centrafricaine','Centrafricaine',236,1),
         ('CHL', 'Chili','Chilienne',56,1),
         ('CHN', 'Chine','Chinoise',86,1),
         ('CYP', 'Chypre','Chypriote',357,1),
         ('COL', 'Colombie','Colombienne',57,1),
         ('COM', 'Comores','Comorienne',269,1),
	 ('COG', 'Congo-Brazzaville','Brazzavilloise',242,1),
	 ('COD', 'Congo-Kinshasa','Kinoise',243,1),
         ('PRK', 'Corée du Nord','Nord-Coréenne',850,1),
         ('KOR', 'Corée du Sud','Sud-Coréenne',82,1),
         ('CRI', 'Costa Rica','Costaricienne',506,1),
	 ('CIV', 'Côte d’Ivoire','Ivoirienne',225,1),
         ('HRV', 'Croatie','Croate',385,1),
         ('CUB', 'Cuba','Cubaine',53,1),
         ('DNK', 'Danemark','Danoise',45,1),
         ('DMA', 'Dominique','Dominicaine',1,1),
	 ('DJI', 'Djibouti','Djiboutienne',253,1),
	 ('EGY', 'Égypte','Égyptienne',20,1),
         ('ARE', 'Émirats arabes unis','Émiratie',971,1),
         ('ECU', 'Équateur','Équatorienne',593,1),
	 ('ERI', 'Érythrée','Érythréenne',291,1),
         ('ESP', 'Espagne','Espagnole',34,1),
         ('EST', 'Estonie','Estonienne',372,1),
         ('USA', 'États-Unis','Américaine',1,1),
	 ('SWZ', 'Eswatini','Swazi',268,1),
	 ('ETH', 'Éthiopie','Éthiopienne',251,1),
         ('FJI', 'Fidji','Fidjienne',679,1),
         ('FIN', 'Finlande','Finlandaise',358,1),
         ('FRA', 'France','Française',33,1),
	 ('GAB', 'Gabon',' Gabonaise',241,1),
	 ('GMB', 'Gambie','Gambienne',220,1),
         ('GE0', 'Géorgie','Géorgienne',995,1),
	 ('GH',  'Ghana','Ghanéenne',233,1),
         ('GRC', 'Grèce','Grecque',30,1),
         ('GRD', 'Grenade','Grenadienne',1,1),
         ('GTM', 'Guatemala','Guatémaltèque',502,1),
	 ('GNB', 'Guinée-Bissau','Bissau-Guinéenne',245,1),
	 ('GIN', 'Guinée-Conakry ','Guinéenne',224,1),
	 ('GQ',  'Guinée équatoriale','Équato-Guinéenne',240,1),
         ('GUY', ' Guyana','Guyanienne',592,1),
         ('HTI', 'Haïti','Haïtienne',509,1),
         ('HND', 'Honduras','Hondurienne',504,1),
         ('HUN', 'Hongrie','Hongroise',36,1),
         ('IND', 'Inde','Indienne',91,1),
         ('IDN', 'Indonésie','Indonésienne',62,1),
         ('IRQ', 'Irak','Iraquienne',964,1),
         ('IRN', 'Iran','Iranienne',98,1),
         ('IRL', 'Irlande','Irlandaise',353,1),
         ('ISL', 'Islande','Islandaise',354,1),
         ('ISR', 'Israël','Israélienne',972,1),
         ('ITA', 'Italie','Italienne',39,1),
         ('JAM', 'Jamaïque','Jamaïcaine',1,1),
         ('JPN', 'Japon','Japonaise',81,1),
         ('JOR', 'Jordanie','Jordanienne',962,1),
         ('KAZ', 'Kazakhstan','Kazakh',7,1),
	 ('KEN', 'Kénya','Kényane',254,1),
         ('KGZ', 'Kirghizistan','Kirghize',996,1),
         ('KIR', 'Kiribati','Kiribatienne',686,1),
         ('XK',  'Kosovo','Kosovare',383,1),
         ('KWT', 'Koweït','Koweïtienne',965,1),
         ('LAO', 'Laos','Laotienne',856,1),
	 ('LSO', 'Lesotho','Lesothane',266,1),
         ('LVA', 'Lettonie','Lettonne',371,1),
         ('LBN', 'Liban','Libanaise',961,1),
	 ('LR',  'Libéria','Libérienne',231,1),
	 ('LBY', 'Libye','Libyenne',218,1),
         ('LIE', 'Liechtenstein','Liechtensteinoise',423,1),
         ('LTU', 'Lituanie','Lituanienne',370,1),
         ('LUX', 'Luxembourg','Luxembourgeoise',352,1),
         ('MKD', 'Macédoine','Macédonienne',389,1),
         ('MYS', 'Malaisie','Malaisienne',60,1),
         ('MWI', 'Malawi','Malawite',265,1),
         ('MDV', 'Maldives','Maldivienne',960,1),
	 ('MDG', 'Madagascar','Malgache',261,1),
	 ('MWI', 'Malawi','Malawite',265,1),
	 ('MLI', 'Mali','Malienne',223,1),
         ('MLT', 'Malte','Maltaise',356,1),
	 ('MAR', 'Maroc','Marocaine',212,1),
         ('MHL', 'Marshall','Marshallaise',692,1),
	 ('MUS', 'Maurice','Mauricienne',230,1),
	 ('MRT', 'Mauritanie','Mauritanienne',222,1),
         ('MEX', 'Mexique','Mexicaine',52,1),
         ('FSM', 'Micronésie','Micronésienne',691,1),
         ('MDA', 'Moldavie','Moldave',373,1),
         ('MCO', 'Monaco','Monégasque',377,1),
         ('MNG', 'Mongolie','Mongole',976,1),
         ('MNE', 'Monténégro','Monténégrine',382,1),
	 ('MOZ', 'Mozambique','Mozambicaine',258,1),
	 ('NAM', 'Namibie','Namibienne',264,1),
         ('NRU', 'Nauru','Nauruane',674,1),
         ('NPL', 'Népal','Népalaise',977,1),
         ('NIC', 'Nicaragua','Nicaraguayenne',505,1),
	 ('NER', 'Niger','Nigérienne',227,1),
	 ('NGA', 'Nigéria','Nigériane',234,1),
         ('NOR', 'Norvège','Norvégienne',47,1),
         ('NZL', 'Nouvelle-Zélande','Néo-Zélandaise', 64,1),
         ('OMN', 'Oman','Omanaise',968,1),
         ('UZB', 'Ouzbékistan','Ouzbek', 998,1),
         ('PAK', 'Pakistan', 'Pakistanaise',92,1),
         ('PAN', 'Panama', 'Panaméenne',507,1),
         ('PG',  'Papouasie-Nouvelle-Guinée', 'Papouan-néo-guinéenne',675,1),
         ('PRY', 'Paraguay','Paraguayen',595,1),
         ('NLD', 'Pays-Bas','Hollandais',31,1),
         ('PER', 'Pérou','Péruvienne',51,1),
         ('PHL', 'Philippines','Philippine',63,1),
         ('POL', 'Pologne','Polonaise',48,1),
         ('PRT', 'Portugal','Portugaise',351,1),
         ('QAT', 'Qatar','Qatarie',974,1),
         ('DOM', 'République dominicaine','Dominicaine',1,1),
         ('CZE', 'République tchèque','Tchèque',420,1),
         ('ROU', 'Roumanie','Roumaine',40,1),
         ('GBR', 'Royaume-Uni', 'Britannique',44,1),
         ('RUS', 'Russie', 'Russe', 7,1),
	 ('UGA', 'Ouganda','Ougandais',256,1),
	 ('RW',  'Rwanda','Rwandaise',250,1),
         ('KNA', 'Saint-Christophe-et-Niévès','Christophienne',1,1),
         ('LCA', 'Sainte-Lucie','Sainte-Lucienne',1,1),
         ('SMR', 'Saint-Marin','saint-marinaise',378,1),
         ('VCT', 'Saint-Vincent-et-les-Grenadines','Vincentaise',1,1),
         ('SLB', 'Salomon','Salomonaise',677,1),
	 ('STP', 'São Tomé-et-Principe','Santoméenne',239,1),
         ('SLV', 'Salvador', 'Salvadorienne',503,1),
         ('WSM', 'Samoa occidentales','Samoane',685,1),
	 ('SEN', 'Sénégal','Sénégalaise',221,1),
         ('SRB', 'Serbie','Serbe',381,1),
	 ('SYC', 'Seychelles','Seychelloise',248,1),
	 ('SLE', 'Sierra Leone','Sierra-Léonaise',232,1),
         ('SGP', 'Singapour','Singapourienne',65,1),
         ('SVK', 'Slovaquie','Slovaque',421,1),
         ('SVN', 'Slovénie','Slovène',386,1),
	 ('SOM', 'Somalie','Somalienne',252,1),
         ('SDN', 'Soudan','Soudanaise',249,1),
	 ('SSD', 'Soudan du Sud','Sud-Soudanaise',211,1),
         ('LKA', 'Sri Lanka','Sri Lankaise',94,1),
         ('SWE', 'Suède','Suédoise',46,1),
         ('CHE', 'Suisse','Suisse',41,1),
         ('SUR', 'Surinam','Surinamaise',597,1),
         ('SWZ', 'Swaziland','Swazis',268,1),
         ('SYR', 'Syrie','Syrien',963,1),
         ('TJK', 'Tadjikistan','tadjik',992,1),
	 ('TZA', 'Tanzanie','Tanzanienne',255,1),
	 ('TCD', 'Tchad','Tchadienne',235,1),
         ('TLS', 'Timor oriental','Timoraise',670,1),
         ('THA', 'Thaïlande','Thaïlandaise',66,1),
	 ('TGO', 'Togo','Togolaise',228,1),
         ('TON', 'Tonga','Tongienne',676,1),
         ('TTO', 'Trinité-et-Tobago','Trinidadienne',1,1),
	 ('TUN', 'Tunisie','Tunisienne',216,1),
         ('TKM', 'Turkménistan','Turkmène',993,1),
         ('TUR', 'Turquie', 'Turc', 90,1),
         ('TUV', 'Tuvalu', 'Tuvaluane',688,1),
         ('UKR', 'Ukraine', 'Ukrainienne',380,1),
         ('URY', 'Uruguay', 'Uruguayenne',598,1),
         ('VUT', 'Vanuatu', 'Vanuataise', 678,1),
         ('VAT', 'Vatican', 'Vaticanaise',379,1),
         ('VEN', 'Venezuela', 'Vénézuélienne',58,1),
         ('VNM', 'Vietnam', 'vietnamienne',84,1),
         ('YEM', 'Yémen', 'Yéménite', 967,1),
	 ('ZMB', 'Zambie','Zambienne',260,1),
	 ('ZWE', 'Zimbabwe','Zimbabwéenne',263,1)
    ON CONFLICT DO NOTHING;
    END IF;
END $$;
